---
sudo: required
services:
  - docker
language: python
python:
  - "2.6"
  - "2.7"
env:
  global:
    - OS_NAME=centos
  matrix:
    - OS_MAJOR_VERSION=6
    - OS_MAJOR_VERSION=7
before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt update
  - sudo apt install -y docker-ce
  - docker --version
install:
  - wget http://archive.ubuntu.com/ubuntu/pool/universe/r/rpmlint/rpmlint_1.7-1_all.deb
  - sudo dpkg -i rpmlint_1.7-1_all.deb || sudo apt install -f -y
  - gem install mdl
  - if [[  $TRAVIS_PYTHON_VERSION == 2.6 ]]; then pip install 'flake8<3.0.0'; fi
  - if [[  $TRAVIS_PYTHON_VERSION == 2.7 ]]; then pip install flake8 flake8-import-order hacking; fi
script:
  # First syntax, linting and pre-test stages
  - mdl -s relaxed README.md
  - rpmlint bdii.spec
  - flake8 bin/bdii-update
  # Then, start the build container
  - docker run --name build_container -d -ti -v $PWD:/src -w /src $OS_NAME:$OS_MAJOR_VERSION sh -c 'while true ; do sleep 1000 ; done'
  # Now, install prerequisites for the build
  - docker exec -i -w /root build_container yum install -y rpm-build rpmlint make rsync
  # Eventually build the rpm
  - docker exec -i -w /src build_container make rpm
  # lint the RPM
  - docker exec -i -w /src/build build_container rpmlint --option UseVarLockSubsys=False --option UseVarLockSubsys='tuple(default=list(0o644, 0o755, 0o640))' RPMS/
  # Now, start the test container
  - docker run --name install_container -d -ti -v $PWD:/src -w /src $OS_NAME:$OS_MAJOR_VERSION sh -c 'while true ; do sleep 1000 ; done'
  # and install it
  - docker exec -i -w /src/build/RPMS/noarch install_container yum install -y epel-release
  - docker exec -i -w /src/build/RPMS/noarch install_container sh -c "yum localinstall -y bdii*.el${OS_MAJOR_VERSION}.noarch.rpm"
deploy:
  provider: releases
  api_key:
    secure: tw560GrnanaDUSQ27wmyn+tryv7NYwvKjafc23VWpJRw78BYrIZopAL3r/YN9k7iQmk0WyJ7pjV3ayL/XSW0vYhCme1hpKaKTrRl8r+C4pJcmz9q50bVE1G2invgiqiw2Tpne7BG/LS7aERQxPs2tgmzvoy0XLFgoWOec+cBts5D+KtAnOZ5jxob6V9K1na79pK9OK4mVt/rYeuqEb8O44tjHywa7PWzg9mHAtzAGLtrgki3ICEosFkqRyBaQmwbLc/fUhA1De9TtGtbxaQ3GYRCIgnQTJ5DNOcuj3X21WlXGhQXEovR1oC3lBwMPxx2Ap1Ke3JNIU9y8YiW7CGqQm8XV9wm5PFN6O2ZccjPRVp+xkGkl0w1+RL/Ms2zfevFaxztqzKCt+AVXDw4aQrxyawuNCRLku3uzzQa0cQPfJscWHAqLCTXSP13hbKyyu+nvVFBpMjY6xO8TICHeb5dXVOU1JIw6Qu+AqfEIYZQsNuJI6SUwkkonHrRZ0iEfLi+0JQ8adelGqCfDiK7bDSFQ4prjLECjjp3HHSrvvcRNl8gEc+0P/qdWsIdC8j1a332f3VsO3JF/8+NWjU2Uy8fs04DyzWM4l3Ccg+7DEfx/zdPWCwlzNq6giByMiDm0RvPgrNVigdN8o6QnVOxkpeL4lNnOVfIb/RtJq4ND3zKvOE=
  file_glob: true
  file:
    - build/RPMS/noarch/bdii*.el${OS_MAJOR_VERSION}.noarch.rpm
    - build/SRPMS/bdii*.el${OS_MAJOR_VERSION}.src.rpm
  on:
    tags: true
