#!/bin/sh

cat << EOF
dn: GLUE2ServiceID=urn:ogf:ComputingService:pd.infn.it:cream-06,GLUE2GroupID=resource,o=glue
GLUE2EntityCreationTime: 2011-02-07T10:57:48Z
GLUE2EntityValidity: 60
GLUE2EntityName: cream-06
objectClass: GLUE2Service
GLUE2ServiceID: urn:ogf:ComputingService:pd.infn.it:cream-06
GLUE2ServiceCapability: executionmanagement.jobexecution
GLUE2ServiceType: org.nordugrid.execution.arex
GLUE2ServiceQualityLevel: development
GLUE2ServiceComplexity: endpoint=1,share=4,resource=1
GLUE2ServiceAdminDomainForeignKey: urn:ogf:AdminDomain:pd.infn.it
objectClass: GLUE2ComputingService
GLUE2ComputingServiceTotalJobs: 0
GLUE2ComputingServiceRunningJobs: 0
GLUE2ComputingServiceWaitingJobs: 0
GLUE2ComputingServiceStagingJobs: 0
GLUE2ComputingServiceSuspendedJobs: 0
GLUE2ComputingServicePreLRMSWaitingJobs: 0

EOF