#!/bin/sh
cat <<EOF
dn: GlueServiceUniqueID=service_2,mds-vo-name=resource,o=grid
objectClass: GlueTop
objectClass: GlueService
objectClass: GlueKey
objectClass: GlueSchemaVersion
GlueServiceUniqueID: service_2
GlueServiceName: Test Service Two
GlueServiceType: bdii
GlueServiceVersion: 3.0.0
GlueServiceEndpoint: ldap://host-invalid:2170/mds-vo-name=resource,o=grid
GlueServiceStatus: OK
GlueServiceStatusInfo: BDII Runnning
GlueServiceAccessControlBaseRule: dteam
GlueForeignKey: GlueSiteUniqueID=my-site-name
GlueSchemaVersionMajor: 1
GlueSchemaVersionMinor: 3

EOF
