#!/bin/sh
cat <<EOF
dn: GlueServiceUniqueID=service_1,mds-vo-name=resource,o=grid
changetype: modify
add: GlueServiceAccessControlBaseRule
GlueServiceAccessControlBaseRule: cms
-
replace: GlueServiceStatusInfo
GlueServiceStatusInfo: BDII Broken

EOF
