---
name: Create packages and test installation

on:
  pull_request:

jobs:
  build-centos7:
    name: Build CentOS 7 RPMs
    runs-on: ubuntu-latest
    container: quay.io/centos/centos:7
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install build requisites
        run: |
          yum install -y rpm-build rpmlint make rsync
      - name: build rpm
        run: |
          make clean rpm
          rpmlint --file .rpmlint.ini build/RPMS/noarch/*.rpm
      - name: Upload RPMs
        uses: actions/upload-artifact@v3
        with:
          name: rpms7
          path: |
            build/RPMS/noarch/bdii-*.el7.noarch.rpm

  build-almalinux8:
    name: Build AlmaLinux 8 RPMs
    runs-on: ubuntu-latest
    container: almalinux:8
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install build requisites
        run: |
          yum install -y rpm-build rpmlint make rsync
      - name: build rpm
        run: |
          make clean rpm
          rpmlint --file .rpmlint.ini build/RPMS/noarch/*.rpm
      - name: Upload RPMs
        uses: actions/upload-artifact@v3
        with:
          name: rpms8
          path: |
            build/RPMS/noarch/bdii-*.el8.noarch.rpm

  build-almalinux9:
    name: Build AlmaLinux 9 RPMs
    runs-on: ubuntu-latest
    container: almalinux:9
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install build requisites
        run: |
          yum install -y rpm-build rpmlint make rsync systemd-rpm-macros
      - name: build rpm
        run: |
          make clean rpm
          rpmlint --file .rpmlint.ini build/RPMS/noarch/*.rpm
      - name: Upload RPMs
        uses: actions/upload-artifact@v3
        with:
          name: rpms9
          path: |
            build/RPMS/noarch/bdii-*.el9.noarch.rpm

  # XXX Dependency from EPEL: glue-schema
  install-centos7:
    name: Install CentOS 7 RPMs
    needs: build-centos7
    runs-on: ubuntu-latest
    container: quay.io/centos/centos:7
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: rpms7
      - name: Install generated RPMs
        run: |
          yum install -y epel-release
          yum localinstall -y bdii-*.el7.noarch.rpm

  # XXX Dependency from EPEL: glue-schema
  # FIXME: openldap-servers is in CentOS 8 Stream Powertools, but not in AlmaLinux PowerTools
  # See https://bugs.almalinux.org/view.php?id=222
  # Currently instaling using the package from devel repository
  # See https://bugs.almalinux.org/view.php?id=100
  # https://repo.almalinux.org/almalinux/8/devel/x86_64/os/Packages/
  install-almalinux8:
    name: Install AlmaLinux 8 RPMs
    needs: build-almalinux8
    runs-on: ubuntu-latest
    container: almalinux:8
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: rpms8
      - name: Install generated RPMs
        run: |
          yum install -y epel-release
          yum install -y https://repo.almalinux.org/almalinux/8/devel/x86_64/os/Packages/openldap-servers-2.4.46-18.el8.x86_64.rpm
          yum localinstall -y bdii-*.el8.noarch.rpm

  # XXX Dependencies from EPEL: glue-schema, openldap-servers
  install-almalinux9:
    name: Install AlmaLinux 9 RPMs
    needs: build-almalinux9
    runs-on: ubuntu-latest
    container: almalinux:9
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: rpms9
      - name: Install generated RPMs
        run: |
          yum install -y epel-release
          yum localinstall -y bdii-*.el9.noarch.rpm
