name: Create packages and test installation

on:
  pull_request:

jobs:
  centos7:
    name: build centos 7 rpms
    runs-on: ubuntu-latest
    container: centos:7
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: install build requisites
        run: |
          yum install -y rpm-build rpmlint make rsync
      - name: build rpm
        run: |
          make rpm
          rpmlint --file .rpmlint.ini build/RPMS/noarch/*.rpm
      - name: Upload rpms
        uses: actions/upload-artifact@v2
        with:
          name: rpms
          path: |
            RPMS/noarch/bdii-*-1.el7.noarch.rpm

  centos7-install:
    name: install centos 7 rpms
    needs: centos7
    runs-on: ubuntu-latest
    container: centos:7
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: rpms
      - name: install generated rpms
        run: |
          yum localinstall -y bdii-*.rpm
