---
# When a tag is created
# - create a new release from the tag
# - build and attach packages to the release
name: Create packages and release

on:
  push:
    tags:
      - "v*"

jobs:
  centos7:
    name: Build centOS 7 rpms
    runs-on: ubuntu-latest
    container: centos:7
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: install build requisites
        run: |
          yum install -y rpm-build rpmlint make rsync
      - name: build rpm
        run: |
          make rpm
          rpmlint --file .rpmlint.ini build/RPMS/noarch/*.rpm
      - name: Upload rpms
        uses: actions/upload-artifact@v2
        with:
          name: rpms
          path: |
            build/RPMS/noarch/bdii-*-1.el7.noarch.rpm
            build/SRPMS/bdii-*-1.el7.src.rpm

  release:
    name: Upload release artefacts
    needs: centos7
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: rpms
      - name: Find package name
        id: package_name
        run: |
          rpm_name=$(ls bdii-*-1.el7.noarch.rpm)
          src_name=$(ls bdii-*-1.el7.src.rpm)
          echo ::set-output name=rpm_name::$rpm_name
          echo ::set-output name=src_name::$src_name
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
      - name: Upload BDII rpm
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./${{ steps.package_name.outputs.rpm_name }}
          asset_name: ${{ steps.package_name.outputs.rpm_name }}
          asset_content_type: application/octet-stream
      - name: Upload BDII source rpm
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./${{ steps.package_name.outputs.src_name }}
          asset_name: ${{ steps.package_name.outputs.src_name }}
          asset_content_type: application/octet-stream
