---
# When a tag is created
# - create a new release from the tag
# - build and attach packages to the release
name: Create packages and release

on:
  push:
    tags:
      - "v*"

jobs:
  centos7:
    name: build centos 7 rpms
    runs-on: ubuntu-latest
    container: centos:7
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: install build requisites
        run: |
          yum install -y rpm-build rpmlint make rsync
      - name: build rpm
        run: |
          make rpm
          rpmlint --file .rpmlint.ini build/RPMS/noarch/*.rpm
      - name: Upload rpms
        uses: actions/upload-artifact@v2
        with:
          name: rpms
          path: |
            build/RPMS/noarch/bdii-*-1.el7.noarch.rpm

  release:
    name: Upload release artefacts
    needs: centos7
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: rpms
      - name: Find package name
        id: package_name
        run: |
          package_name=$(ls bdii-*-1.el7.noarch.rpm)
          echo ::set-output name=package_name::$name
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
      - name: Upload base rpm
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # This pulls from the CREATE RELEASE step above, referencing it's ID
          # to get its outputs object, which include a `upload_url`. See this
          # blog post for more info:
          # https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./${{ steps.package_name.outputs.name }}
          asset_name: ${{ steps.package_name.outputs.name }}
          asset_content_type: application/octet-stream
